# This file was generated by GoReleaser. DO NOT EDIT.
cask "openstatus" do
  name "openstatus"
  desc "OpenStatus CLI"
  homepage "https://www.openstatus.dev"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openstatus"
  manpage "docs/openstatus.1"

  on_macos do
    on_intel do
      url "https://github.com/openstatusHQ/cli/releases/download/v#{version}/cli_Darwin_x86_64.tar.gz"
      sha256 "8a1d9a977d6864805733dc2efc9a1df09983aa2cbe7d2277fefc4938a615a4d3"
    end
    on_arm do
      url "https://github.com/openstatusHQ/cli/releases/download/v#{version}/cli_Darwin_arm64.tar.gz"
      sha256 "e3f112e9a666db07abde215cc52990c2e58deb3b37565ed747ae32b057926f6b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/openstatusHQ/cli/releases/download/v#{version}/cli_Linux_x86_64.tar.gz"
      sha256 "78a0222471342a2b16030b5b43ca3864179f30826273210e276c6250df58dc76"
    end
    on_arm do
      url "https://github.com/openstatusHQ/cli/releases/download/v#{version}/cli_Linux_arm64.tar.gz"
      sha256 "5c2bd4567c1957489b3f24b0ed256f6c193dcd2c6fcc0f7a653f7751fe8f7d3e"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # replace 'foo' with the actual binary name
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openstatus"]
    end
  end

  # No zap stanza required
end
