# This file was generated by GoReleaser. DO NOT EDIT.
cask "openstatus" do
  desc "OpenStatus CLI"
  homepage "https://www.openstatus.dev"
  version "0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openstatus"
  manpage "docs/openstatus.1"

  on_macos do
    on_intel do
      url "https://github.com/openstatusHQ/cli/releases/download/v0.0.6/cli_Darwin_x86_64.tar.gz"
      sha256 "cb002b7c86809c2dba10f7c2365ba2f4b6b734866af12e17a4cc546c98651ecc"
    end
    on_arm do
      url "https://github.com/openstatusHQ/cli/releases/download/v0.0.6/cli_Darwin_arm64.tar.gz"
      sha256 "4aaf4bfe83773a2a27cd12e56742afee3bb375c90b0bff9f11c93043cb596670"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/openstatusHQ/cli/releases/download/v0.0.6/cli_Linux_x86_64.tar.gz"
      sha256 "a18b2fb4ef46431231c87074b31c207e8f07ad1c4254ece80524592dbd2c841b"
    end
    on_arm do
      url "https://github.com/openstatusHQ/cli/releases/download/v0.0.6/cli_Linux_arm64.tar.gz"
      sha256 "8e4396d138c5f34f5e93cd750561baa3f704c263cf5c5e00652e4e5f95abe8a8"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # replace 'foo' with the actual binary name
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openstatus"]
    end
  end

  # No zap stanza required
end
