# This file was generated by GoReleaser. DO NOT EDIT.
cask "openstatus" do
  version "1.0.3"

  on_macos do
    on_intel do
      url "https://github.com/openstatusHQ/cli/releases/download/v#{version}/cli_Darwin_x86_64.tar.gz"
      sha256 "f38f70c4cfeb8f701af2869f148dab75e0a22569528af3bf0df03ca4b59bfbc2"
    end
    on_arm do
      url "https://github.com/openstatusHQ/cli/releases/download/v#{version}/cli_Darwin_arm64.tar.gz"
      sha256 "46fdcf7fc9edbad19b5f98410da17436a61274464b9030049079b3c4b1034f91"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/openstatusHQ/cli/releases/download/v#{version}/cli_Linux_x86_64.tar.gz"
      sha256 "80298629d97e839fe4a8f6a4b4a7e32ca575bb1efc19529ed3e22ccd56f18ded"
    end
    on_arm do
      url "https://github.com/openstatusHQ/cli/releases/download/v#{version}/cli_Linux_arm64.tar.gz"
      sha256 "29e6c7b4430194bac631d105a588c720ce7736cebcb3cc4cf73082a3c908ba61"
    end
  end

  name "openstatus"
  desc "OpenStatus CLI"
  homepage "https://www.openstatus.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openstatus"
  manpage "docs/openstatus.1"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # replace 'foo' with the actual binary name
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openstatus"]
    end
  end

  # No zap stanza required

end
