# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openstatus < Formula
  desc "OpenStatus CLI"
  homepage "https://www.openstatus.dev"
  version "0.0.0"

  on_macos do
    on_intel do
      url "https://github.com/openstatusHQ/cli/releases/download/v0.0.0/cli_Darwin_x86_64.tar.gz"
      sha256 "57feda4ee118bab96dc7099437b351ad333099aea5dbc4d4013b20d57d9801f5"

      def install
        bin.install "openstatus"
      end
    end
    on_arm do
      url "https://github.com/openstatusHQ/cli/releases/download/v0.0.0/cli_Darwin_arm64.tar.gz"
      sha256 "4361c4b006e7d6c84f45df875b3f04a149bcc3201ad44d7c3c6d0fa6146f0b06"

      def install
        bin.install "openstatus"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/openstatusHQ/cli/releases/download/v0.0.0/cli_Linux_x86_64.tar.gz"
        sha256 "d373afbd2db383f72fcfaae61a86146494debadcba3ecc342a7125f01a43596d"

        def install
          bin.install "openstatus"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/openstatusHQ/cli/releases/download/v0.0.0/cli_Linux_arm64.tar.gz"
        sha256 "040f7fbeda4b6b29d6b5bed5c4e3d1c6275319b20e52e30bcf3b9976618ea6f6"

        def install
          bin.install "openstatus"
        end
      end
    end
  end

  test do
    system "#{bin}/openstatus --help"
  end
end
