# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openstatus < Formula
  desc ""
  homepage "https://www.openstatus.dev"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openstatusHQ/cli/releases/download/v0.0.5/cli_Darwin_x86_64.tar.gz"
      sha256 "dcf524055c0abd6a2b8f4d3ff146c2d3d780aa3461c72d04291881f75436c7a8"

      def install
        bin.install "openstatus"
        man1.install "openstatus-docs.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openstatusHQ/cli/releases/download/v0.0.5/cli_Darwin_arm64.tar.gz"
      sha256 "09fd835698c755db8d98d692a5a1db3f25634cb2f5cc27a3306561acced27400"

      def install
        bin.install "openstatus"
        man1.install "openstatus-docs.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/openstatusHQ/cli/releases/download/v0.0.5/cli_Linux_x86_64.tar.gz"
      sha256 "8cbb17d93192ea35e6854bf666db579937605c024c9cd5de50c1ba5a3fa5c8ca"
      def install
        bin.install "openstatus"
        man1.install "openstatus-docs.1"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/openstatusHQ/cli/releases/download/v0.0.5/cli_Linux_arm64.tar.gz"
      sha256 "e86f22c62581b64920715d1c795380fafef2b4be20cda52152bb23d6e0192c26"
      def install
        bin.install "openstatus"
        man1.install "openstatus-docs.1"
      end
    end
  end

  test do
    system "#{bin}/openstatus --help"
  end
end
